### PR TITLE
Build library using bili

### PR DESCRIPTION
**Pull request by vladimyr**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

This PR brings in changes in build system & accompanying documentation updates in order to produce and support ESM, CJS and UMD build artifacts. (continuation of #264)

**What is the current behavior? (You can also link to an open issue here)**

Currently only UMD build is produced.

**What is the new behavior (if this is a feature change)?**

ESM, CJS and UMD build artifacts are being created and distributed together with sourcemaps.

**Does this PR introduce a breaking change?**

No.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows semantic-release [guidelines](https://github.com/semantic-release/semantic-release#commit-message-format)
- [x] Fix/Feature: Docs have been added/updated
- [x] Fix/Feature: Tests have been added; existing tests pass

### CODE REVIEW

**Comment by vladimyr** [comment]
Commenting to prevent stale bot from closing it.

**Comment by MatteoGabriele** [comment]
uh the good old stale bot! ahahahahha I will have a look asap! 
bit of a chaotic week, sorry man! 

thanks for your work

**Comment by vladimyr** [comment]
Sure, take your time 👍

**Comment by MatteoGabriele** [comment]
hey @vladimyr I think i'm not going to merge this one because I am about to deprecate the package on npm and it wouldn't make sense to drop a feature that might need some fixes if something happens and then at the same time call it deprecated 🤔

**Comment by vladimyr** [comment]
> hey @vladimyr I think i'm not going to merge this one because I am about to deprecate the package on npm and it wouldn't make sense to drop a feature that might need some fixes if something happens and then at the same time call it deprecated 🤔

1. If you deprecate something it doesn't mean that all a sudden all projects that are using it are gonna switch to the alternate library because that is a simply unrealistic expectation. It is practically impossible to build a case for such change inside an almost completed project. If you go back and read https://github.com/MatteoGabriele/vue-analytics/pull/264#issuecomment-573409725 you'll see that is exactly my case.

2. Calling it a feature is plain and simply wrong. It doesn't change how the library behaves nor offers any new functionality. It is not a feature it is a chore, albeit very much needed and useful one.

3. If that change causes more issues to surface thus requiring more work to be made well that doesn't mean it shouldn't be done in the first place. EOL transition isn't exactly a headshot fire and if it requires some work it is all part of the price you are committed to pay once you started it in the first place. I get it is not something that is fun and you are not eager to do it but nobody ever said that maintaining OSS is an easy task.

At the end of the day, it is your call and I can't really affect it nor I'm entitled to any outcome but your argumentation here is weak and off.

**Comment by MatteoGabriele** [comment]
No, off course I'm not going to pretend a switch to the other library, but lately I don't have time to maintain two libraries that do basically the same thing. Gtag is also the successor of analytics, in Google's plan, so it does make sense . Off course they support all of them but I'm not Google 😂

I don't have to necessarily deprecate it tho

**Comment by vladimyr** [comment]
Fair enough, so why don't you try to find a new maintainer then? Raise an issue, add a link to the readme, throw a word on r/javascript or some other online place and see if someone is willing to take the baton...

I'm perfectly ok to wait for the new maintainer to merge this. After I've waited for months already it doesn't really make any difference to wait for a few more. 😀

**Comment by MatteoGabriele** [comment]
it's not really easy to find a maintainer. you have seen in the past how people just get access to repository and start making a mess or, even worse, introducing security issues.
Open source is a nice community but it is also a very sketchy one

**Comment by vladimyr** [comment]
One could ask why it should be an easy task. It is not that easy but it is also not impossible and I fail to see why it is relevant unless the ultimate goal was to stop thinking about this project yesterday, so to speak.
TBH I see very little potential for `event-stream` type of drama here but regardless of my opinion, it would be nice to explore possibilities prior to stepping into conclusions.

**Comment by MatteoGabriele** [comment]
I feel you're going a bit too far, to be honest. no need to get agitated here.
I have 2 project that do exactly the same thing with two version of the same product so I want to keep focus on one of the two: the more up to date.
that's it!

**Pull request closed without merging**
