### PR TITLE
onAnalyticsReady promise now rejects if ga scripts cannot load

### PR DESCRIPTION
**Pull request by BenjjinF**
**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x ] The commit message follows semantic-release [guidelines](https://github.com/semantic-release/semantic-release#commit-message-format)
- [x ] Fix/Feature: Docs have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

### CODE REVIEW

**Comment by MatteoGabriele** [comment]
hi @BenjjinF 
don't understand this PR and also you checked the commit messages requirements but you didn't actually write the correct messages so this PR.

**Comment by BenjjinF** [comment]
Problem 1: Users are inconsistently tracked if an app loads before vue-analytics is ready
Solution 1: Mount the app after the onAnalyticsReady promise is resolved
Problem 2: Some ad blockers prevent the onAnalyticsReady promise from resolving and, therefore, the app never mounts.

Solution:
This PR differentiates between when the scripts have not loaded yet and when they will not. That way, the onAnalyticsReady promise can reject and developers can choose how to proceed; in my case, just mount the app any...

**Comment by MatteoGabriele** [comment]
As soon as you install vue-analytics, the script already saves events that later on will be fired: this is part of normal google analytics behavior.
Mounting the app when vue-analytics it's ready could be very slow and it's not needed, but you can do it if you like it.

ad-block is not mine/your issue: if a user decides to kill all analytic library, he's free to do so, your application mount shouldn't depend on a third-party optional library.
Example: in the EU all analytics libraries need to be opt-in/opt-out by law, so could be that analytics doesn't have to run, so the app should mount either way.

**Comment by BenjjinF** [comment]
Ideally, I wouldn't have to mount the app like that but, otherwise, google analytics was only able to track a minority of hits. I wasn't able to determine exactly why, but my theory is that only very slow devices that couldn't finish mounting before vue-analytics was ready were tracked.

Maybe we have different user bases. A large proportion of mine have no idea what ad-block is; if the browser they're using has one enabled it is not of their own doing. We have to work with the constraints we are given and this PR removes one of them.

**Comment by MatteoGabriele** [comment]
I will think about this, but also the commit message is still wrong so either way I can't accept this pr

**Pull request closed without merging**
