### PR TITLE
fix(bootstrap): apply any sets before delivering untracked events

### PR DESCRIPTION
**Pull request by ericcirone**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug Fix.

**What is the current behavior? (You can also link to an open issue here)**
https://github.com/MatteoGabriele/vue-analytics/issues/188

**What is the new behavior (if this is a feature change)?**
All set's get applied before any events get dispatched to google analytics

**Does this PR introduce a breaking change?**
no

**Please check if the PR fulfills these requirements**
- [X] The commit message follows semantic-release [guidelines](https://github.com/semantic-release/semantic-release#commit-message-format)
- [ ] Fix/Feature: Docs have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

### CODE REVIEW

**Comment by MatteoGabriele** [comment]
Sorry but the commit message is wrong, it wont trigger the build for the NPM release. Could you please change it?

thanks a lot :)

**Comment by ericcirone** [comment]
hopefully that is better

**Comment by MatteoGabriele** [comment]
I was talking about the commit message "Make sure collectors are set before reporting any events to google."

**Comment by ericcirone** [comment]
ok did that fix it for ya?

**Comment by MatteoGabriele** [comment]
Yes man, perfect!
It should be published in less then 5 minutes

Thanks again

**Comment by ericcirone** [comment]
sweet!

**Pull request merged**
