### PR TITLE
Vuex middleware property check

### PR DESCRIPTION
**Pull request by Bob-Thomas**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix for #138 

**What is the current behavior? (You can also link to an open issue here)**
#138 

**What is the new behavior (if this is a feature change)?**
No more assuming that meta always contains analytics

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x] The commit message follows semantic-release [guidelines](https://github.com/semantic-release/semantic-release#commit-message-format)
- [x] Fix/Feature: Docs have been added/updated
- [x] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

### CODE REVIEW

**Comment by MatteoGabriele** [comment]
@Bob-Thomas thank's a lot for your contribution!

**Comment by MatteoGabriele** [comment]
I don't know why but TracisCI didn't trigger the proper script after the test block and so it didn't publish it. I'm trying to see what's wrong because the commits messages are correct

**Comment by Bob-Thomas** [comment]
@MatteoGabriele No problem happy to help out. Is TravisCI still broken or is everything okay ?

**Comment by MatteoGabriele** [comment]
Yeah I couldn't fix the build process and now I'm busy, I'll probably check later today. I'll let you know

**Pull request merged**
