### PR TITLE
Object literal syntax

### PR DESCRIPTION
**Pull request by MosheAtOwal**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
docs update

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows semantic-release [guidelines](https://github.com/semantic-release/semantic-release#commit-message-format)
- [x] Fix/Feature: Docs have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

### CODE REVIEW

**Comment by MatteoGabriele** [comment]
I'm sorry but the commit message doesn't follow the same pattern described in the PR requirements

Thanks for your time :)

**Comment by MosheAtOwal** [comment]
Whoops, let me take a look. Apologies!

**Comment by MosheAtOwal** [comment]
Superseded by #141.

**Comment by MatteoGabriele** [comment]
No worries at all

I'll close this PR, already merge the content update in another PR

**Pull request closed without merging**
