### PR TITLE
Build and distribute ESM, CJS and UMD artifacts

### PR DESCRIPTION
**Pull request by vladimyr**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

This PR brings in changes in build system & accompanying documentation updates in order to produce and support ESM, CJS and UMD build artifacts.

**What is the current behavior? (You can also link to an open issue here)**

Currently only UMD build is produced.

**What is the new behavior (if this is a feature change)?**

ESM, CJS and UMD build artifacts are being created and distributed together with sourcemaps.

**Does this PR introduce a breaking change?**

No.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows semantic-release [guidelines](https://github.com/semantic-release/semantic-release#commit-message-format)
- [x] Fix/Feature: Docs have been added/updated
- [x] Fix/Feature: Tests have been added; existing tests pass

### CODE REVIEW

**Comment by vladimyr** [comment]
@MatteoGabriele In the end I decided going with rollup instead of webpack because it is easy enough and more natural choice in case of bundling libraries.

**Comment by MatteoGabriele** [comment]
same decision for the vue-gtag package.
especially for this one to be honest I don't feel like changing the compiler right now.
in the vue-gtag it will probably be done and maybe once I figure the best implementation i'll drop it here too

thanks a lot for your time

**Comment by vladimyr** [comment]
@MatteoGabriele Would it be acceptabe if I make webpack based pr?

**Comment by MatteoGabriele** [comment]
hey @vladimyr sorry for the delay. yes maybe a webpack version could be better, without too much complications. would like to have a simple a readable compiler, that's why I wanted to take time.
Lots of time happened that a certain point i couldn't understand what was happening anymore: they get messy very quickly honestly.

thanks a lot, if you want to do it or not

cheers

**Comment by MatteoGabriele** [comment]
@vladimyr I'm trying to use a package called `bili` made by the good old Egoist and it just does everything in 2 lines. so if that one works well I might do that here too

**Comment by vladimyr** [comment]
Well this is interesting 🙃 You went full circle from my handmade rollup config to bili that is essentially a rollup wrapper - _standard_ rollup config generator and a runner. Bili is usually my first choice (open PRs there and see yourself) but I took bare rollup route due to:
1. You used custom written webpack config for vue-analytics while you could leverage good old egoist's poi: https://poi.js.org/ So I assumed it (bili/poi type of tool) is probably too much for your preference.
2. Trying to cover many usecases it comes with many rollup plugins _bundled_ thus increasing dependency tree and install time in developer setup.
3. I'm still waiting for egoist to switch bili to newly crated/migrated official rollup plugins, e.g. https://www.npmjs.com/package/rollup-plugin-json
However that is seriously good news and please go for it! *And please do it for both repos.* I actually never fully explained my motivation so there you go. Your default webpack config generates umd-min without sourcemaps (plus exotic gz which I personally found useless but nvm let's leave that alone). That is problematic due to:
1. You don't distribute sourcemaps. Now imagine what pain is to debug your module as part of a larger app and that is exactly what my team got into.
2. Because ultimately/most likely your library will end up inside other's app bundles it means that webpack (or their bundler of choice) would try to optimize already minified umd source. It immediately makes tree shaking no go and webpack will warn you against doing it because it is bad from optimization perspective in general.
So as long as you distribute sourcemap/s and have package.json's module pointed to es (not minified!) and optionally main to cjs variant it will all be sunshines and roses 😃

**Comment by MatteoGabriele** [comment]
I get it and I saw that issue with the new rollup switch to namespaced packages, I guess it's an easy fix for him.
the thing about sourcemaps is that I never see them in any other packages: was checking vue distribution and they don't have them, for example
I'll make sure to output as many files possible so that people can choose indeed

thanks for the feedback, really appreciated

**Comment by vladimyr** [comment]
Easy fix for very busy man and writing test for it wasn't that easy 🙃
Well you can easily live without them if you distribute non-minified single file es/cjs variants which vue does.
You are welcome, if you need any help with it, let me know 😉

**Comment by MatteoGabriele** [comment]
Yeah I guess is has a hell of a schedule 😂
Thanks man

**Pull request closed without merging**
